### PR TITLE
Add support for piping commands in CLI

### PR DESCRIPTION
**Pull request by WilliamVoong**
Here is a commit that allows seqdia to use pipes like this! 
echo "Alice -> Bob: hello world" | seqdia

This also makes it possible to call it from vim using :h filter.

### CODE REVIEW

**Comment by WilliamVoong** [comment]
Hmm seems like i found a small bug in my code, preparing a new commit.

**Comment by WilliamVoong** [comment]
Done and tested :)

**Comment by Ja-sonYun** [comment]
@WilliamVoong I really appreciate your contribution.
Please remove the binary file before merge this PR.

**Comment by Ja-sonYun** [comment]
Oh wait, there was a binary file even in this repository...

**Comment by WilliamVoong** [comment]
> @WilliamVoong I really appreciate your contribution. Please remove the binary file before merge this PR.

Done!

**Pull request merged**
